### ISSUE TITLE
Problem with ϊέναι 

### ISSUE THREAD

**Issue by arsimr16** [homermultitext/byzortho#1011]
In the byzortho/orthoequivs list, ϊέναι is listed six times (urn:cite:hmt:normalized.161, urn:cite:hmt:normalized.253, urn:cite:hmt:normalized.301, urn:cite:hmt:normalized.142, urn:cite:hmt:normalized.234, urn:cite:hmt:normalized.657) with the proposed equivalent ἰέναι.  The word is still failing in validation.  I also noticed that below these proposed equivalents, there is another entry for ί̈ενται (urn:cite:hmt:normalized.2039) with an incorrect equivalent ἵ̈ενται.  There should not be a diaeresis on the proposed equivalent.  Should we remove five of the proposed equivalents for ϊέναι and correct the equivalent for ί̈ενται?  Also, we need to figure out why ϊέναι is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ῗφι.  It was proposed twice as being equivalent to ἶφι (urn:cite:hmt:normalized.1295, urn:cite:hmt:normalized.788) and it is still failing in validation.

**Comment by arsimr16** [comment]
Same thing happened with ῆεν.  It was proposed five times as being equivalent to ἦεν (urn:cite:hmt:normalized.102, urn:cite:hmt:normalized.194, urn:cite:hmt:normalized.895, urn:cite:hmt:normalized.930, urn:cite:hmt:normalized.981) and is still failing validation.

**Comment by mwauke** [comment]
Same thing happened with όπλων. It was proposed five times as being equivalent to όπλων (urn:cite:hmt:normalized.2002) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with όπλων. It was proposed five times as being equivalent to όπλων (urn:cite:hmt:normalized.62) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with άρα. It was proposed as being equivalent to ἄρα (urn:cite:hmt:normalized.62) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with ήμισυ. It was proposed twice as being equivalent to ἥμισυ (urn:cite:hmt:normalized.170; urn:cite:hmt:normalized.262) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with άλα. It was proposedas being equivalent to ἅλα (urn:cite:hmt:normalized.2012) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with ΐκοντο. It was proposed as being equivalent to ἵκοντο (urn:cite:hmt:normalized.982) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with ΐκετο. It was proposed as being equivalent to ἵκετο (urn:cite:hmt:normalized.1856) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with εθέλεσκε. It was proposed as being equivalent to ἐθέλεσκε (urn:cite:hmt:normalized.117) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with αλωῆς. It was proposed as being equivalent to ἀλωῆς (urn:cite:hmt:normalized.2310) and is still failing validation

**Comment by mwauke** [comment]
Same thing happened with ατυχίᾳ. It was proposed as being equivalent to ἀτυχίᾳ (urn:cite:hmt:normalized.2342) and is still failing validation

**Comment by mwauke** [comment]
Same thing happened with ώρμαινε. It was proposed as being equivalent to ὥρμαινε (urn:cite:hmt:normalized.2317) and is still failing validation

**Comment by mwauke** [comment]
Same thing happened with ήσχυνε. It was proposed as being equivalent to ᾔσχυνε (urn:cite:hmt:normalized.2316) and is still failing validation

**Comment by arsimr16** [comment]
Same thing happened with αναστρεπτέον.  It was proposed as being equivalent to ἀναστρεπτέον (urn:cite:hmt:normalized.1516) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with εξῆς.  It was proposed four times as being equivalent to ἑξῆς (urn:cite:hmt:normalized.1170, urn:cite:hmt:normalized.505, urn:cite:hmt:normalized.556, urn:cite:hmt:normalized.958) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ιδίαν.  It was proposed as being equivalent to ἰδίαν (urn:cite:hmt:normalized.2184) and is still failing validation.

**Comment by mwauke** [comment]
Same thing happened with υἱος. It was proposed as being equivalent to υἱός (urn:cite:hmt:normalized.368) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with έτι. It was proposed as being equivalent to ἔτι (urn:cite:hmt:normalized.1091) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with έστασαν.  It was proposed as being equivalent to ἔστασαν (see issue #1066), but it should not have failed validation because  έστασαν appears twice as being equivalent to ἕστασαν (urn:cite:hmt:normalized.814, urn:cite:hmt:normalized.858).  If we want to read this verb with a smooth breathing, we can add a new equivalent to the list, but the word should not have failed validation in the first place.  Regardless of whether we add a new equivalent with a smooth breathing or not, we still need to remove one of the equivalents for ἕστασαν because the same equivalent pair should not be listed twice.

**Comment by cjschu17** [comment]
Same thing happened with ΐκετ'. It was proposed as being equivalent to ἵκετ' (urn:cite:hmt:normalized.1868) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with αῖαν.  It was proposed twice as being equivalent to αἶαν (urn:cite:hmt:normalized.147, urn:cite:hmt:normalized.239) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with αυτῷ.  It was proposed four times as being equivalent to αὐτῷ (urn:cite:hmt:normalized.1035, urn:cite:hmt:normalized.116, urn:cite:hmt:normalized.208, urn:cite:hmt:normalized.818) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ἡλιου.  It was proposed as being equivalent to ἡλίου (urn:cite:hmt:normalized.3) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ἠτήσατο.  It was proposed as being equivalent to ᾐτήσατο (urn:cite:hmt:normalized.1723) and is still failing validation.

**Comment by cjschu17** [comment]
Same thing happened with ὐφ. It was proposed as being equivalent to ὑφ' (urn:cite:hmt:normalized.2307) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with έμεναι.  It was proposed as being equivalent to ἔμεναι (urn:cite:hmt:normalized.71) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ΐκετο.  It was proposed as being equivalent to ἵκετο (urn:cite:hmt:normalized.1856) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with οὐδε.  It was proposed three times as being equivalent to οὐδέ (urn:cite:hmt:normalized.514, urn:cite:hmt:normalized.734, urn:cite:hmt:normalized.833) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with ένια.  It was proposed twice as being equivalent to ἔνια (urn:cite:hmt:normalized.1529, urn:cite:hmt:normalized.1651) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with έλαβε.  It was proposed as being equivalent to ἔλαβε (urn:cite:hmt:normalized.2348) and is still failing validation.

**Comment by arsimr16** [comment]
Same thing happened with έλσαι.  It was proposed as being equivalent to ἔλσαι (urn:cite:hmt:byzortho.2861) and is still failing validation.

**Comment by brclar15** [comment]
Same thing happened with ϊκεσθαι. It was proposed as  being equivalent to ἱκέσθαι three times (urn:cite:hmt:byzortho.1, urn:cite:hmt:byzortho.173, urn:cite:hmt:byzortho.265) and is still failing validation.

**Comment by mwauke** [comment]
Same thing happened with όλου. It was proposed as being equivalent to ὅλου (urn:cite:hmt:byzortho.2160) and is still failing validation.

**Comment by neelsmith** [comment]
Remarkably, not a single comment in this long thread includes a reference to a passage of text on a physical page.  I'm assuming that all they examples are of the same type as the one resolved in the hmt-utils tracker in issue https://github.com/homermultitext/hmt-utils/issues/122 and closing this issue.

If problems come up that require additions to the byzortho authority list, they should be submitted here;  if they look like parsing/data reading issues, they should go in the future to hmt-utils tracker.
