### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.243v έστασαν

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/byzortho#1066]
urn:cts:greekLit:tlg0012.tlg001.msA:18.233

surface form: έστασαν

normalized form: ἔστασαν

**Comment by arsimr16** [comment]
The missing breathing can be either smooth or rough depending on whether you want the verb to be aorist or pluperfect.  έστασαν has already been proposed twice as being equivalent to ἕστασαν (with a rough breathing) (urn:cite:hmt:normalized.814, urn:cite:hmt:normalized.858).  We can either keep the proposed normalized form and add ἔστασαν (smooth breathing) to the byzortho/orthoequivs list, or we can change the proposed normalized form to have a rough breathing in which case we would not need to add another equivalent to the list.  Either way the form έστασαν should not be failing so there is a problem with the validation.
