### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.242v αναστρεφέσθαι

### ISSUE THREAD

**Issue by mwauke** [homermultitext/byzortho#1081]
urn:cts:greekLit:tlg5026.msA:18.67

surface form: αναστρεφέσθαι

normalized form: ἀναστρεφέσθαι

**Comment by mwauke** [comment]
added

urn:cite:hmt:normalized.2467

**Comment by cjschu17** [comment]
REJECTED. 

Accent goes on antepenult. Sic tag it.
