### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.247r αίητον

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1164]
urn:cts:greekLit:tlg0012.tlg001.msA:18.410
urn:cts:greekLit:tlg5026.msA.hmt:18.141
urn:cts:greekLit:tlg5026.msA.hmt:18.141
urn:cts:greekLit:tlg5026.msA.hmt:18.144

surface form: αίητον

normalized form: αἴητον

**Comment by mwauke** [comment]
added

urn:cite:hmt:normalized.2499
