### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.253v ΐκετ'

### ISSUE THREAD

**Issue by abeckwit** [homermultitext/byzortho#1173]
urn:cts:greekLit:tlg0012.tlg001.msA:19.115 

surface form: ΐκετ' 

normalized form: ἵκετ'

**Comment by cjschu17** [comment]
already added. 

urn:cite:hmt:normalized.1868

Sometimes the validation system just doesn't work the way we want even when everything is entered correctly. We will add this to our ongoing list of problems:  See issue #1011
