### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.253v προσηύδᾱ

### ISSUE THREAD

**Issue by graceface** [homermultitext/byzortho#1178]
urn:cts:greekLit:tlg0012.tlg001.msA:19.120@προσηύδᾱ[1]
surface form: προσηύδᾱ

normalized form:  προσηύδα

**Comment by cjschu17** [comment]
REJECTED. Macra and brevia currently are not passing validation. We currently have an issue detailing this problem (https://github.com/homermultitext/hmt-utils/issues/37); for now let it fail and it will pass once the issue is fixed.
