### ISSUE TITLE
New orthographical variant urn:cite:hmt:msA.252v ϊῷ

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/byzortho#1202]
surface form ϊῷ
normalized form ἰῷ

urn:cts:greekLit:tlg0012.tlg001.msA:19.59@ϊῷ
urn:cite:hmt:vaimg.VA252VN-0754@0.869,0.3772,0.032,0.021

No breathing mark on the ι.

**Comment by arsimr16** [comment]
added

urn:cite:hmt:normalized.2544
