### ISSUE TITLE
New orthographical variant urn:cite:hmt:msA.252v έγχεος

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/byzortho#1203]
urn:cts:greekLit:tlg0012.tlg001.msA:19.73@έγχεος
urn:cite:hmt:vaimg.VA252VN-0754@0.689,0.6401,0.092,0.0285

surface form έγχεος
normalized form ἔγχεος

**Comment by arsimr16** [comment]
added

urn:cite:hmt:normalized.2545
