### ISSUE TITLE
New orthographic varient urn:cite:hmt:msA.251v εάσωμεν

### ISSUE THREAD

**Issue by cjscan18** [homermultitext/byzortho#1358]
urn:cts:greekLit:tlg5026.msAim.hmt:19.2015office3_1
surface form: εάσωμεν
normalized form: εἄσωμεν

**Comment by mwauke** [comment]
I DON'T CARE WHAT OFFICE YOU'RE IN

**Comment by mwauke** [comment]
added

urn:cite:hmt:normalized.2759
