### ISSUE TITLE
New orthographic varient urn:cite:hmt:msA.251v ήρωασ

### ISSUE THREAD

**Issue by cjscan18** [homermultitext/byzortho#1360]
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office3_2
surface form: ήρωασ 
normalized form: ἥρωασ

**Comment by mwauke** [comment]
Please use a terminal sigma when applicable. You're throwing off my groove 

https://www.youtube.com/watch?v=tePa0CI478k

**Comment by mwauke** [comment]
added

urn:cite:hmt:normalized.2760

**Comment by cjscan18** [comment]
Will do hahah sorry
