### ISSUE TITLE
 New Orthographic Variant urn:cite:hmt:msA.251v αρσινικοῦ

### ISSUE THREAD

**Issue by cjscan18** [homermultitext/byzortho#1368]
urn:cts:greekLit:tlg5026.msA.hmt:19.office3_4
surface form: αρσινικοῦ
normalized form: ἀρσινικοῦ

**Comment by mwauke** [comment]
It looks like in the manuscript it's "αρσενικοῦ" (with an epsilon rather than an iota). Be sure to fix that in your edition.

added

urn:cite:hmt:normalized.2763
