### ISSUE TITLE
 New Orthographic Variant urn:cite:hmt:msA.191r ὑπαι

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/byzortho#1419]
urn:cts:greekLit:tlg5026.msA.hmt:15.6
urn:cts:greekLit:tlg5026.msA.hmt:15.6
urn:cts:greekLit:tlg5026.msA.hmt:15.6
urn:cts:greekLit:tlg5026.msA.hmt:15.7

Surface Form: ὑπαι

Normalized Form: ὑπαὶ

**Comment by arsimr16** [comment]
added

urn:cite:hmt:normalized.2871
