### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.252r νεκροις

### ISSUE THREAD

**Issue by eliaseells** [homermultitext/byzortho#1432]
urn:cts:greekLit:tlg5026.msA.hmt:19.office4_2

surface form: νεκροις

normalized form: νέκροις

**Comment by mwauke** [comment]
REJECTED

"νεκροις" should have a circumflex over the iota. I have added it as normalized: νεκροῖς

urn:cite:hmt:normalized.2838
