### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.252r προςμονογενὲς

### ISSUE THREAD

**Issue by eliaseells** [homermultitext/byzortho#1439]
urn:cts:greekLit:tlg5026.msA.hmt:19.office4_1

surface form: προςμονογενὲς

normalized form: προς μονογενὲς

**Comment by cjschu17** [comment]
REJECTED.

Just write the words in the XML as two separate words and do not worry about the fact that προς has no accent. It has already been added to the Byzortho without an accent (urn:cite:hmt:normalized.1607).
