### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.253r έλκεος

### ISSUE THREAD

**Issue by ulalian** [homermultitext/byzortho#1448]
urn:cite:hmt:vaimg.VA253RN-0424@0.57,0.1277,0.033,0.0128
Surface Form: έλκεος
Normalized Form: with smooth breathing over first epsilon

**Comment by cjschu17** [comment]
Did you mean a rough breathing? A smooth breathing doesn't parse.

**Comment by cjschu17** [comment]
urn:cite:hmt:normalized.2823 added for ἕλκεος with a rough breathing pending any word supporting a smooth breathing.

**Comment by ulalian** [comment]
yes, thank you
