### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.253r ὑβάλλειν

### ISSUE THREAD

**Issue by ulalian** [homermultitext/byzortho#1450]
ὑβάλλειν - incorrect spelling on MA 
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office9_3@ὑβάλλειν[1]

**Comment by cjschu17** [comment]
REJECTED. The word should be wrapped in a "sic" tag.

Byzortho equivalents typically apply only to words that are missing things like accents, breathing marks, diaereses, etc. Mistakes in any of these things or any misspellings are not considered Byzantine equivalents, but rather treated as mistakes on the manuscript and wrapped in a "sic" to indicate that it is truly how it appears on the manuscript while acknowledging its divergence from our standard lexicon.
