### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.253r εστῶτος

### ISSUE THREAD

**Issue by ulalian** [homermultitext/byzortho#1451]
εστῶτος - wants a rough breathing urn:cts:greekLit:tlg5026.msA.hmt:19.2015office9_3@εστῶτος[1]

**Comment by ulalian** [comment]
εσταότος - wants a smooth breathing urn:cts:greekLit:tlg5026.msA.hmt:19.2015office9_3@εσταότος[1]

**Comment by cjschu17** [comment]
urn:cite:hmt:normalized.2820 added for εστῶτος

**Comment by cjschu17** [comment]
ἐσταότος with a smooth breathing does not parse, yet ἑσταότος with a rough does. Does this work with your edition?

**Comment by cjschu17** [comment]
urn:cite:hmt:normalized.2824 added for ἑσταότος with a rough breathing, pending any word supporting the smooth breathing.

**Comment by ulalian** [comment]
thank you!
