### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.191r ἀφικηαι

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/byzortho#1480]
urn:cts:greekLit:tlg5026.msA.hmt:15.15

surface: ἀφικηαι

Normalized: ἀφικηαί

**Comment by mwauke** [comment]
REJECTED

 The accent should be on the first iota. I have submitted it as 

urn:cite:hmt:normalized.2966

with the correct normalized form (ἀφίκηαι)
