### ISSUE TITLE
New Orthographic Variant urn:cts:hmt:msA.253v ΐκετ

### ISSUE THREAD

**Issue by cshanley18** [homermultitext/byzortho#1523]
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office10_2

Surface Form: ΐκετ᾽

Normalized Form: ἵκετ᾽

**Comment by arsimr16** [comment]
already added (urn:cite:hmt:normalized.1868)

This word failed validation because it has the wrong elision mark.  Use ' (English apostrophe) instead.
