### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.194r ήμενον

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1711]
urn:cts:greekLit:tlg5026.msA.hmt:15.46@ήμενον[1]
urn:cts:greekLit:tlg5026.msAim.hmt:15.21@ήμενον[1]

surface: ήμενον

norm: ἥμενον

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3228
