### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.194v ῗσόν

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1725]
urn:cts:greekLit:tlg0012.tlg001.msA:15.183@ῗσόν[1]
urn:cts:greekLit:tlg5026.msA.hmt:15.54@ῗσόν[1]

surface: ῗσόν

norm: ἶσόν

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3241
