### ISSUE TITLE
new variant εζεσθεν urn:cite:hmt:msA.102r

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/byzortho#1744]
passage: urn:cts:greekLit:tlg5026.msAint.hmt:8.74
surface: εζεσθεν
normalized: ἕζεσθεν

also submitted to lexmapping, because modern orthography writes it  ἑζέσθην but the scholion explicitly states this alternative spelling

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3260
