### ISSUE TITLE
new variant φαρος  urn:cite:hmt:msA.105r

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/byzortho#1748]
passages:     urn:cts:greekLit:tlg5026.msA.hmt:8.162@φαρος[1]
    urn:cts:greekLit:tlg5026.msA.hmt:8.162@φαρος[2]
surface: φαρος 
normalized: φάρος

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3266
