### ISSUE TITLE
New variant ενώπια urn:cite:hmt:msA.109r

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/byzortho#1781]
passages:    urn:cts:greekLit:tlg0012.tlg001.msA:8.435@ενώπια[1]
    urn:cts:greekLit:tlg5026.msA.hmt:8.271@ενώπια[1]
    urn:cts:greekLit:tlg5026.msA.hmt:8.271@ενώπια[2]
surface: ενώπια
normalized: ἐνώπια

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3300
