### ISSUE TITLE
New Ortho urn:cite:hmt:msA.42r ΐησιν

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1854]
urn:cts:greekLit:tlg0012.tlg001.msA:3.12@ΐησιν
urn:cts:greekLit:tlg5026.msA.hmt:3.23@ΐησιν

surface: ΐησιν

norm: ἵησιν

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3413
