### ISSUE TITLE
New Ortho urn:cite:hmt:msA.42r ἀκουουσι

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1865]
urn:cts:greekLit:tlg5026.msA.hmt:3.23

surf: ἀκουουσι

norm: ἀκούουσι

**Comment by cjschu17** [comment]
rejected. I think the "ου" in question is abbreviated, and therefore doesn't need to have an accent with it. Please let me know if I'm wrong, and let you look at it again, but I think you can just change the XML.

**Comment by cjschu17** [comment]
urn:cite:hmt:vaimg.VA042RN-0043@0.594,0.4493,0.055,0.0188

the word in question

**Comment by brclar15** [comment]
Great Scotts, excellent point. thats why we do this. Clearly you were trained by the best, @ncchur ought to be very proud.

I'll change the XML now
