### ISSUE TITLE
New Ortho urn:cite:hmt:msA.42v εῖλε

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1889]
urn:cts:greekLit:tlg0012.tlg001.msA:3.35

surfÑ εῖλε

normÑ εἶλε

**Comment by cjschu17** [comment]
are you sure it's εἶλε and not εἷλε? The text on Perseus has it as εἷλε and it makes sense in context. "ὦχρός τέ μιν εἷλε παρειά" would be "the paleness of the cheek took him" which makes more sense than "the paleness of the cheek shut him out"

**Comment by brclar15** [comment]
ah you're so right, and so good Charlie. Sorry for my typo
thanks for doing all of these!

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3449
