### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.102v: αντελάβετο

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/byzortho#189]
passages: urn:cts:greekLit:tlg5026.msA.hmt:8.81 and
urn:cts:greekLit:tlg5026.msA.hmt:8.82
surface: αντελάβετο
normalized: ἀντελάβετο

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3114
