### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v όπασσον

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1895]
urn:cts:greekLit:tlg0012.tlg001.msA:16.38

urn:cite:hmt:vaimg.VA206VN-0708@0.881,0.4583,0.061,0.0233

surf: όπασσον

norm: ὄπασσον

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3450
