### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v έμε

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1896]
urn:cts:greekLit:tlg0012.tlg001.msA:16.41

urn:cite:hmt:vaimg.VA206VN-0708@0.552,0.5154,0.051,0.0233

surf: έμε

norm: ἐμέ

**Comment by arsimr16** [comment]
Not a Byzortho because the accent is present and incorrect.  This would be a Byzortho if the accent were missing.
