### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v κ

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1897]
urn:cts:greekLit:tlg0012.tlg001.msA:16.41

> urn:cite:hmt:vaimg.VA206VN-0708@0.534,0.5154,0.03,0.0225

surf: κ 

norm: κ'

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3451,κ,κ',proposed,
