### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v δυο

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1898]
urn:cts:greekLit:tlg5026.msA.hmt:16.B10

> urn:cite:hmt:vaimg.VA206VN-0708@0.4337,0.8191,0.0232,0.016

surf: δυο

norm: δύο

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3452,δυο,δύο,proposed,
