### ISSUE TITLE
New Ortho urn:cite:hmt:msA.42v ἀπo

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#1899]
urn:cts:greekLit:tlg5026.msA.hmt:3.68@ἀπo[1]
urn:cts:greekLit:tlg5026.msA.hmt:3.95@ἀπo[1]

surf: ἀπo

norm: ἀπό

it did fail, even though i'd except it to already be in the otrtho list....

**Comment by arsimr16** [comment]
Your expectations were correct.  It is (mistakenly) on the Byzortho list twice already.  I'm not sure why it is still failing.
