### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v οῖσι

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1918]
urn:cts:greekLit:tlg5026.msA.hmt:16.B11
urn:cite:hmt:vaimg.VA206VN-0708@0.7859,0.8494,0.0435,0.0147

surf: οῖσι

norm: οἶσι

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3468
