### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ὀδυσσεία

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1919]
urn:cts:greekLit:tlg5026.msA.hmt:16.B11

urn:cite:hmt:vaimg.VA206VN-0708@0.5451,0.8452,0.0454,0.0136

surf: ὀδυσσεία

norm: Ὀδυσσεία

**Comment by arsimr16** [comment]
This is not a Byzortho.  You can enter it into the XML with a capital omicron.  Is the word wrapped in a title element?  If it isn't, that might be why it is failing.
