### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ονήσεται

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1921]
urn:cts:greekLit:tlg5026.msA.hmt:16.B4

urn:cite:hmt:vaimg.VA206VN-0708@0.8042,0.1583,0.0376,0.0097

surf: ονήσεται

norm: ὀνήσεται

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3469
