### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v έρεσθαι

### ISSUE THREAD

**Issue by emmettvb** [homermultitext/byzortho#1922]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

surf: έρεσθαι

norm: ἐρέσθαι

**Comment by JaneyCapers** [comment]
urn:cite:hmt:vaimg.VA206VN-0708@0.755,0.1995,0.0359,0.0136

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3470
