### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v αιτεῖ

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1923]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.2831,0.3451,0.0295,0.0091

surf: αιτεῖ

norm: αἰτεῖ

**Comment by cjschu17** [comment]
added

urn:cite:hmt:byzortho.3742
