### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v διπλου

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1924]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.2882,0.4121,0.0265,0.0094

surf: διπλου

norm: δίπλου

**Comment by cjschu17** [comment]
Added
urn:cite:hmt:byzortho.3471

But I changed the normalized form to διπλοῦ instead of δίπλου. The former was recognized by Morpheus, the latter was not.
