### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v εῖχε

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1925]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.4098,0.2641,0.0221,0.0138

surf: εῖχε

norm: εἶχε

**Comment by cjschu17** [comment]
urn:cite:hmt:byzortho.3473

added
