### ISSUE TITLE
 Edit New issue New orthographic Variant urn:cite:hmt:msA.206v οξείαν

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1926]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.3124,0.2279,0.0361,0.0122

surf: οξείαν

norm: ὀξέαν

**Comment by cjschu17** [comment]
REJECTED

οξείαν should have a circumflex, not an acute.

urn:cite:hmt:byzortho.1374
