### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v οριστικοῦ

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1927]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.3273,0.1758,0.0474,0.0115

surf: οριστικοῦ

norm: ὁριστικοῦ

**Comment by cjschu17** [comment]
urn:cite:hmt:byzortho.3475

added
