### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ἔρεσθαι

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1928]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.3687,0.2849,0.0371,0.0163

surf: ἔρεσθαι

norm: ἐρέσθαι

**Comment by cjschu17** [comment]
REJECTED. You should put a <sic> tag around it. The Byzortho standards for accents says that if the acccent is wrong, it's just wrong not a Byzortho.
