### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v αθάνατα

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1929]
urn:cts:greekLit:tlg5026.msA.hmt:16.B7

urn:cite:hmt:vaimg.VA206VN-0708@0.2639,0.5981,0.0383,0.0112

surf: αθάνατα

norm: ἀθάνατα

**Comment by mwauke** [comment]
Added

urn:cite:hmt:byzortho.3484
