### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v διδαξας

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1930]
urn:cts:greekLit:tlg5026.msA.hmt:16.B7

urn:cite:hmt:vaimg.VA206VN-0708@0.4218,0.6567,0.0413,0.0131

surf: διδαξας

norm: δίδαξας

**Comment by mwauke** [comment]
Added

urn:cite:hmt:byzortho.3483

However, I changed the normalized form to διδάξας rather than δίδαξας.
