### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ενεγκὼν

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1931]
urn:cts:greekLit:tlg5026.msA.hmt:16.B7

urn:cite:hmt:vaimg.VA206VN-0708@0.3478,0.6341,0.0271,0.0138

surf: ενεγκὼν

norm: ἐνεγκὼν

**Comment by mwauke** [comment]
Added

urn:cite:hmt:byzortho.3482
