### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ϊατρικὴν

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1932]
urn:cts:greekLit:tlg5026.msA.hmt:16.B7

urn:cite:hmt:vaimg.VA206VN-0708@0.2756,0.6676,0.0378,0.0134

surf: ϊατρικὴν

norm: ἰατρικὴν

**Comment by mwauke** [comment]
Already added 

urn:cite:hmt:byzortho.1398
