### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ΐσκοντες

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1933]
urn:cts:greekLit:tlg5026.msA.hmt:16.B8 and B9

urn:cite:hmt:vaimg.VA206VN-0708@0.6062,0.7385,0.0494,0.0175

surf: ΐσκοντες

norm: ἴ̈σκοντες

**Comment by mwauke** [comment]
Added

urn:cite:hmt:byzortho.3481
