### ISSUE TITLE
New orthographic Variant urn:cite:hmt:msA.206v ΐσκεν

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1934]
urn:cts:greekLit:tlg5026.msA.hmt:16.B8

urn:cite:hmt:vaimg.VA206VN-0708@0.7497,0.7524,0.0262,0.0159

surf: ΐσκεν

norm: ἴ̈σκεν

**Comment by mwauke** [comment]
Added

urn:cite:hmt:byzortho.3480

But took out diaeresis in normalized form
