### ISSUE TITLE
New issue New orthographic Variant urn:cite:hmt:msA.206v οξείαν

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/byzortho#1935]
urn:cts:greekLit:tlg5026.msA.hmt:16.B5

urn:cite:hmt:vaimg.VA206VN-0708@0.3124,0.2279,0.0361,0.0122

surf: οξείαν

norm: ὀξεῖαν

**Comment by mwauke** [comment]
REJECTED

If the surface form has the incorrect accent (as opposed to no accent), then wrap it in a <sic>
