### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.175r ούρεσι

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/byzortho#1940]
urn:cts:greekLit:tlg5026.msA.hmt:13.571

urn:cite:hmt:vaimg.VA175RN-0346@0.423,0.4733,0.055,0.0188

surf: ούρεσι

norm: οὔρεσι

**Comment by cshanley18** [comment]
urn:cite:hmt:byzortho.3485

added
