### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.175r εθέλοντα

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/byzortho#1941]
urn:cts:greekLit:tlg5026.msA.hmt:13.572

urn:cite:hmt:vaimg.VA175RN-0346@0.312,0.4861,0.08,0.0188

surf: εθέλοντα

norm: ἐθέλοντα

**Comment by cjschu17** [comment]
urn:cite:hmt:byzortho.3486

added
