### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.175r ήλασε

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/byzortho#1943]
urn:cts:greekLit:tlg5026.msA.hmt:13.576

urn:cite:hmt:vaimg.VA175RN-0346@0.479,0.5672,0.063,0.021

surf: ήλασε

norm: ἤλασε

**Comment by cjschu17** [comment]
urn:cite:hmt:byzortho.3488

added
