### ISSUE TITLE
New Orthographic Variant: urn:cite:hmt:e3.136v ὤρνυθ

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#247]
*fixed to reflect the manuscript. 

surface form: ὤρνυθ
normalized form: ὤρνυθ'

folio urn: urn:cite:hmt:e3.136v
passage urn: urn:cts:greekLit:tlg0012.tlg001.e3:11.2

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3149
