### ISSUE TITLE
New Orthographic Variant: urn:cite:hmt:e3.143r: εκείνῃ

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#271]
folio urn: urn:cite:hmt:e3.143r
passage urn: urn:cts:greekLit:tlg5026.e3.hmt:11.123

surface form:  εκείνῃ
normalized form:  ἐκείνῃ

**Comment by arsimr16** [comment]
added

urn:cite:hmt:byzortho.3150
