### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.145r: εφάψηται

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/byzortho#464]
passage: urn:cts:greekLit:tlg5026.msAil.hmt:11.185
surface: εφάψηται 
normalized: ἐγάψηται

**Comment by arsimr16** [comment]
This should be marked in a sic

**Comment by arsimr16** [comment]
εφάψηται is a valid byzortho.  The normalized form should be ἐφάψηται.

added

urn:cite:hmt:byzortho.3155
