### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.154v: έχειν 

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#821]
Passage URN: urn:cts:greekLit:tlg5026.msA:12.A11
Surface Form: έχειν
Normalized Form: ἔχειν

It's right here: http://beta.hpcc.uh.edu/tomcat/hmt-digital/images?request=GetIIPMooViewer&urn=urn:cite:hmt:vaimg.VA154VN-0656@0.6256,0.7107,0.037,0.0225

**Comment by arsimr16** [comment]
already added

urn:cite:hmt:normalized.2471
