### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.159v: ορθοὺς  

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#855]
passage: urn:cts:greekLit:tlg5026.msAil.hmt:12.H20 and urn:cts:greekLit:tlg5026.msA.hmt:12.H21

surface:  ορθοὺς 
normalized: ὀρθοὺς

**Comment by arsimr16** [comment]
added

urn:cite:hmt:normalized.2689
