### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.239r αγωνιζομενῶν

### ISSUE THREAD

**Issue by brclar15** [homermultitext/byzortho#973]
urn:cts:greekLit:tlg5026.msA.hmt:18.7

surface form: αγωνιζομενῶν

normalized form: ἀγωνιζομενῶν

**Comment by cjschu17** [comment]
added

urn:cite:hmt:normalized.2339,αγωνιζομενῶν,ἀγωνιζομενῶν,proposed,
